replicaCount: 1

image:
  repository: vladimirkhil/sistatisticsservice
  pullPolicy: IfNotPresent
  tag: 1.2.0

nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

podSecurityContext: {}

service:
  type: ClusterIP
  port: 5000
  targetPort: 5000

ingress:
  enabled: true
  className: "nginx"
  clientSecret: ''
  annotations: {}
  hosts: []
  tls: []

resources: {}

logPath: ''

database:
  host: ''
  name: 'sistatistics'
  user: 'postgres'
  passwordKey: ''
  passwordValue: 'postgres-password'
  backup:
    enabled: false
    schedule: '0 0 * * *' # Run every day at midnight
    imageVersion: 15
    securityContext: {}
    volumePath: ''

options:
  topPackageCount: 10
  maxResultCount: 100
  logLevel: Warning
  otel:
    uri: 'http://localhost:4317'
    metric:
      exportInterval: 60000
