replicaCount: 1

image:
  repository: vladimirkhil/sistatisticsservice
  pullPolicy: IfNotPresent
  tag: "1.0.8"

nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

podSecurityContext: {}

service:
  type: ClusterIP
  port: 5000
  targetPort: 5000

ingress:
  enabled: true
  className: "nginx"
  clientSecret: ''
  annotations: {}
  hosts: []
  tls: []

resources: {}

logPath: ''

database:
  host: ''
  name: 'sistatistics'
  user: 'postgres'
  passwordKey: ''
  passwordValue: 'postgres-password'

options:
  topPackageCount: 10
  maxResultCount: 100
  logLevel: Warning
