version: "3.9"

services:

  postgres:
    image: postgres:15.0
    ports:
      - 5432:5432
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}

  sistatistics:
    image: vladimirkhil/sistatisticsservice:${SERVICE_TAG}
    ports:
      - 5057:8080
    volumes:
      - ./log:/app/log
    environment:
      - "ConnectionStrings__SIStatistics=${DB_CONNECTION}"
    depends_on:
      - postgres